# %run

In [2]:
%run ./hello.py

Hello Machine Learning !


In [3]:
hello("imooc")

Hello imooc !


In [4]:
import mymodule.predict

In [5]:
mymodule.predict.predict(1)

?


# %timeit 多次平均

In [6]:
%timeit L=[i**2 for i in range(1000)]

341 µs ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%timeit L=[i**2 for i in range(100000)]

30.2 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit L=[i**2 for i in range(10)]

3.62 µs ± 216 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%%timeit
L=[]
for n in range(1000):
    L.append(n**2)

344 µs ± 15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# %time  一次测量

In [10]:
%time
L=[i**2 for i in range(1000)]

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs


In [11]:
import random
L=[random.random() for i in range(100000)]
%timeit L.sort()

532 µs ± 66.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
%time L.sort()

CPU times: user 1.25 ms, sys: 17 µs, total: 1.27 ms
Wall time: 1.28 ms


In [13]:
import numpy

In [14]:
numpy.__version__

'1.15.4'

## Numpy

In [15]:
import numpy as np

In [16]:
import array

In [17]:
arr = array.array("i",[i for i in range(10)])

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.array

In [19]:
nparr=np.array([i for i in range(10)])

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5]=100

In [22]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [27]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
 np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linsplace

In [32]:
np.linspace(0,20,10) # 0 , 20 inclusive， 等差数列

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [33]:
np.linspace(0,20,11) # start , end , 截多少个数， 起始 终止 都包括

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [34]:
np.random.randint(0,10,10) # 起始，， 终止 ，个数  左闭右开

array([6, 0, 4, 0, 3, 0, 0, 5, 1, 0])

In [35]:
np.random.randint(4,8,size=(3,5))

array([[4, 7, 6, 4, 4],
       [6, 6, 5, 7, 5],
       [4, 7, 4, 5, 6]])

In [36]:
np.random.randint(4,8,size=(3,5))

array([[7, 5, 4, 6, 4],
       [7, 5, 5, 4, 4],
       [7, 4, 6, 6, 6]])

In [37]:
np.random.seed(666) #保证随机值，可重复

In [38]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [39]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [40]:
np.random.random()

0.7744794542685887

In [41]:
np.random.random((3,5))

array([[0.00510884, 0.11285765, 0.11095367, 0.24766823, 0.0232363 ],
       [0.72732115, 0.34003494, 0.19750316, 0.90917959, 0.97834699],
       [0.53280254, 0.25913185, 0.58381262, 0.32569065, 0.88889931]])

In [42]:
np.random.normal()

1.1413367715995875

In [43]:
np.random.normal(0,1,size=(3,5)) #符合正态分布的随机数矩阵

array([[ 0.45243662, -2.23496877,  1.27047766, -0.72928821,  1.35925255],
       [-1.20990266, -0.04618272, -0.44118244,  0.46953431,  0.44325817],
       [-1.66738875, -1.81731749, -1.39753916,  0.78392691, -0.29129965]])

## numpy.array的基本操作

In [44]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
X=np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## basic proporties

In [46]:
x.ndim

1

In [47]:
X.ndim

2

In [48]:
x.shape

(10,)

In [49]:
X.shape

(3, 5)

In [50]:
x.size

10

In [51]:
X.size

15

## numpy.array 数据访问

In [52]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x[0]

0

In [54]:
x[-1]

9

In [55]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
X[0][0]#不建议 使用

0

In [57]:
X[2,2]

12

In [58]:
X[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
x[0:5]

array([0, 1, 2, 3, 4])

In [60]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
x[::2]

array([0, 2, 4, 6, 8])

In [62]:
x[5:]

array([5, 6, 7, 8, 9])

In [63]:
x[:5]

array([0, 1, 2, 3, 4])

In [64]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [65]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
X[:2][:3] # 不能取到不同维度

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [68]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [69]:
X[0,:]

array([0, 1, 2, 3, 4])

In [70]:
subX=X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [71]:
subX[0,0]=100

In [72]:
X #  修改子矩阵 会改变原矩阵， 反之亦然

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [73]:
X[0,0]=0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [75]:
subX=X[:2,:3].copy() # 用copy就可以解决以上问题
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [76]:
subX[0,0]=100

In [77]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape

In [78]:
x.shape

(10,)

In [79]:
x.ndim

1

In [80]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
A=x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
B=x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [85]:
B.shape

(1, 10)

In [86]:
B.ndim

2

In [87]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [88]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 合并操作

In [90]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [91]:
x

array([1, 2, 3])

In [92]:
y

array([3, 2, 1])

In [93]:
np.concatenate([x,y])#x,y只能用list包括在内才能拼接，不能直接放进去

array([1, 2, 3, 3, 2, 1])

In [94]:
z=np.array([666,666,666])

In [95]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [96]:
A=np.arange(1,7).reshape(2,3)

In [97]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [99]:
np.concatenate([A,A],axis=1) #默认为0 行， 1 为 列 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [100]:
z=z.reshape(1,-1)

In [101]:
A2=np.concatenate([A,z])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [102]:
np.vstack([A,z]) # 垂直拼接

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [103]:
B=np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [104]:
np.hstack([A,B]) #水平拼接

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

##  分割 split

In [105]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
x1,x2,x3=np.split(x,[3,7])
print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [107]:
x1,x2=np.split(x,[5])
print(x1)
print(x2)

[0 1 2 3 4]
[5 6 7 8 9]


In [108]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
A1,A2=np.split(A,[2]) # 基于 维度分割 axis=0 按行分割

In [110]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [111]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
A1,A2=np.split(A,[2],axis=1)

In [113]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [114]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [115]:
upper,lower=np.vsplit(A,[2])

In [116]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [117]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
left,right=np.hsplit(A,[2])

In [119]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [120]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## numpy.array 的运算

In [121]:
n=10
L=[i for i in range(10)]

In [122]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [123]:
A=[]
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [124]:
n=1000000
L=[i for i in range(n)]


In [125]:
%%time
A=[]
for e in L:
    A.append(2*e)
A

CPU times: user 176 ms, sys: 24.6 ms, total: 201 ms
Wall time: 202 ms


In [126]:
%%time
A=[e*2 for e in L]

CPU times: user 87.9 ms, sys: 28.8 ms, total: 117 ms
Wall time: 116 ms


In [127]:
L=np.arange(n)

In [128]:
%%time
A=np.array(e*2 for e in L)

CPU times: user 13.7 ms, sys: 7.47 ms, total: 21.1 ms
Wall time: 21.1 ms


In [129]:
%%time
A=2*L

CPU times: user 4.06 ms, sys: 4.65 ms, total: 8.72 ms
Wall time: 6.73 ms


In [130]:
n=10
L=np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Function

In [131]:
X=np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [132]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [133]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [135]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [136]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [137]:
X**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [138]:
X%2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [139]:
1/X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [140]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [141]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [142]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [143]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [144]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [145]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [146]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [147]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [148]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [149]:
B=np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [150]:
A+B

array([[10, 11],
       [12, 13]])

In [151]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [152]:
A*B

array([[ 0, 10],
       [20, 30]])

In [153]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [154]:
A.dot(B) # matrix multiple

array([[10, 10],
       [50, 50]])

In [155]:
A.T

array([[0, 2],
       [1, 3]])

In [156]:
C=np.full((3,3),666)

In [157]:
A.dot(C) #(2,2) (3,3) 不能相乘

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 矩阵和向量的运算

In [158]:
v=np.array([1,2])

In [159]:
A

array([[0, 1],
       [2, 3]])

In [160]:
v+A

array([[1, 3],
       [3, 5]])

In [161]:
np.vstack([v] * A.shape[0])+A

array([[1, 3],
       [3, 5]])

In [162]:
np.tile(v,(2,1)) #(2,1) 在行叠加两次 列方向叠加一次

array([[1, 2],
       [1, 2]])

In [163]:
v*A

array([[0, 2],
       [2, 6]])

In [164]:
v.dot(A)

array([4, 7])

In [165]:
A.dot(v) # column vector

array([2, 8])

## 矩阵的逆

In [166]:
A

array([[0, 1],
       [2, 3]])

In [167]:
invA=np.linalg.inv(A)

In [168]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [169]:
X=np.arange(16).reshape(2,8)

In [170]:
pinvX=np.linalg.pinv(X) # 伪逆矩阵

In [171]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

## 聚合操作

In [172]:
L=np.random.random(100)
L

array([0.78613657, 0.77138693, 0.42005486, 0.77602514, 0.46430814,
       0.18177017, 0.8840256 , 0.71879227, 0.6718813 , 0.25656363,
       0.43080182, 0.01645358, 0.23499383, 0.51117131, 0.29200924,
       0.50189351, 0.49827313, 0.10377152, 0.44644312, 0.96918917,
       0.73847112, 0.71955061, 0.89304339, 0.96267468, 0.19705023,
       0.71458996, 0.16192394, 0.86625477, 0.62382025, 0.95945512,
       0.52414204, 0.03643288, 0.72687158, 0.00390984, 0.050294  ,
       0.99199232, 0.2122575 , 0.94737066, 0.45154055, 0.99879467,
       0.64750149, 0.70224071, 0.42958177, 0.16777476, 0.11813309,
       0.93788262, 0.91099744, 0.39799354, 0.92530327, 0.74549922,
       0.78982636, 0.63770852, 0.99274137, 0.47610554, 0.10211419,
       0.87256332, 0.75612704, 0.29919884, 0.18625652, 0.49435351,
       0.0408955 , 0.47835228, 0.3089902 , 0.92058026, 0.91794568,
       0.46848893, 0.23431308, 0.08982494, 0.67940357, 0.65592832,
       0.0039444 , 0.06654134, 0.00112109, 0.66608382, 0.38565

In [173]:
sum(L)

52.04049901052246

In [174]:
np.sum(L)

52.04049901052245

In [175]:
big_array=np.random.random(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)#more efficient

7.54 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.5 µs ± 562 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [176]:
np.max(big_array)

0.9999960191873744

In [177]:
big_array.sum()

49935.13467807075

In [178]:
X=np.arange(16).reshape(4,-1)

In [179]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
np.sum(X)

120

In [181]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [182]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [183]:
np.prod(X+1)

20922789888000

In [184]:
np.percentile(big_array,q=100)

0.9999960191873744

In [185]:
for percent in (0,25,50,75,100):
    print(np.percentile(big_array,q=percent))

8.434379650590351e-06
0.24930062831400843
0.4981611651835738
0.7497037230793205
0.9999960191873744


In [186]:
np.var(big_array)

0.08344021576953811

In [187]:
np.std(big_array)

0.2888602010827004

## index 

In [200]:
x=np.random.random(100)

In [201]:
x

array([0.67800115, 0.82411971, 0.12893156, 0.02029581, 0.30059702,
       0.87424965, 0.02757811, 0.37729852, 0.72694578, 0.06613503,
       0.49198378, 0.79199584, 0.58471672, 0.83528109, 0.6295809 ,
       0.18360989, 0.78794218, 0.67957145, 0.20365583, 0.86344995,
       0.70585525, 0.05330393, 0.9289336 , 0.86366799, 0.74987709,
       0.71282244, 0.97133376, 0.30490583, 0.13404265, 0.993156  ,
       0.61567977, 0.14942081, 0.88089145, 0.80234111, 0.97927235,
       0.79378472, 0.10481998, 0.16068806, 0.83520172, 0.50424604,
       0.15993622, 0.42234556, 0.55357417, 0.18394181, 0.08595706,
       0.00642285, 0.26207187, 0.72691855, 0.24938964, 0.32435318,
       0.86901832, 0.32745454, 0.95705161, 0.06684381, 0.7439338 ,
       0.10023782, 0.25746837, 0.85150644, 0.25462407, 0.0518256 ,
       0.73832434, 0.14380254, 0.44451624, 0.80881723, 0.27721438,
       0.37552906, 0.80700395, 0.30956294, 0.41351574, 0.28020874,
       0.5175065 , 0.50252144, 0.30121102, 0.67303858, 0.19956

In [203]:
np.argmin(x)

45

## sort and using index 

In [204]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [206]:
np.random.shuffle(x)
x

array([13,  6,  7,  9,  8,  0,  4,  5, 14, 12,  2, 11,  1,  3, 10, 15])

In [208]:
np.sort(x)
x

array([13,  6,  7,  9,  8,  0,  4,  5, 14, 12,  2, 11,  1,  3, 10, 15])

In [209]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [210]:
X=np.random.randint(10,size=(4,4))

In [211]:
X

array([[9, 1, 9, 9],
       [8, 2, 8, 6],
       [0, 3, 5, 2],
       [9, 5, 7, 2]])

In [214]:
np.sort(X)

array([[1, 9, 9, 9],
       [2, 6, 8, 8],
       [0, 2, 3, 5],
       [2, 5, 7, 9]])

In [213]:
np.sort(X, axis=1)

array([[1, 9, 9, 9],
       [2, 6, 8, 8],
       [0, 2, 3, 5],
       [2, 5, 7, 9]])

In [215]:
np.sort(X, axis=0)

array([[0, 1, 5, 2],
       [8, 2, 7, 2],
       [9, 3, 8, 6],
       [9, 5, 9, 9]])

In [216]:
np.random.shuffle(x)

In [218]:
x

array([ 4,  8,  2,  0,  6, 13,  3,  9, 15, 12,  5, 14,  1, 11, 10,  7])

In [217]:
np.argsort(x) #按索引 排序, 索引数组

array([ 3, 12,  2,  6,  0, 10,  4, 15,  1,  7, 14, 13,  9,  5, 11,  8])

In [219]:
np.partition(x,3) # 分割为两个部分 比 3 小 和比3 大的

array([ 1,  0,  2,  3,  6,  4,  5,  7, 15, 12,  8, 14, 13, 11, 10,  9])

In [220]:
np.argpartition(x,3)# 分割为两个部分 比 3 小 和比3 大的 所对应的索引 index 

array([12,  3,  2,  6,  4,  0, 10, 15,  8,  9,  1, 11,  5, 13, 14,  7])

In [221]:
X

array([[9, 1, 9, 9],
       [8, 2, 8, 6],
       [0, 3, 5, 2],
       [9, 5, 7, 2]])

In [222]:
np.argsort(X,axis=1) # 返回的是索引 按列方向

array([[1, 0, 2, 3],
       [1, 3, 0, 2],
       [0, 3, 1, 2],
       [3, 1, 2, 0]])

In [223]:
np.argsort(X,axis=0) # 返回的是索引

array([[2, 0, 2, 2],
       [1, 1, 3, 3],
       [0, 2, 1, 1],
       [3, 3, 0, 0]])

In [224]:
np.argpartition(X,2,axis=1) # 索引矩阵

array([[1, 0, 2, 3],
       [1, 3, 2, 0],
       [0, 3, 1, 2],
       [3, 1, 2, 0]])

## Fancy indexing

In [226]:
x.sort()

In [227]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [228]:
x[3]

3

In [229]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [230]:
x[3:9:2]

array([3, 5, 7])

In [232]:
ind=[3,5,8]

In [233]:
x[ind]

array([3, 5, 8])

In [234]:
ind=np.array([[0,2],
             [1,3]])

In [235]:
x[ind]

array([[0, 2],
       [1, 3]])

In [237]:
X=x.reshape(4,-1)

In [238]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [239]:
row=np.array([0,1,2])
col=np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [240]:
X[0,col]

array([1, 2, 3])

In [241]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [242]:
col=[True,False,True,True]

In [246]:
X[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [245]:
X[1:3,col] # 对第二列 False的列 不感兴趣 不显示

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## np.array 的比较

In [248]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [247]:
x<3 # x>3 x==3 x!=3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [249]:
2*x == 24 -4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [252]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [253]:
np.sum(x<=3)

4

In [254]:
np.count_nonzero(x<=3)

4

In [255]:
np.any(x==0)

True

In [257]:
np.all(x>=0)

True

In [258]:
np.sum(X%2 ==0)

8

In [259]:
np.sum(X%2 ==0,axis=1)

array([2, 2, 2, 2])

In [260]:
np.sum(X%2 ==0,axis=0)

array([4, 0, 4, 0])

In [261]:
np.sum((x>3)&(x<10))

6

In [262]:
np.sum((x%2==0) | x>10)

6

In [265]:
np.sum(~(x==0)) # ~ not dash means 'not' 

15

In [266]:
X[X[:,3] %3 ==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

Pandas 